### PR TITLE
Ch works or not

### PR DESCRIPTION
**Pull request by carter-harris**

### CODE REVIEW

**Comment by Jessicashinjo** [comment]
:shipit:

**Comment by carter-harris** [comment]
Yo guys, so lots of pluralization nightmares fixed in the config files, the nature of the beast 😑

Also, since I added the nav bar via ng-include in the index.html page, we no longer need a config file for the 'landing' files and it has been deleted. 

Everything is working via the links in the nav bar. We will need to chain some promises to show more when you click albums and tracks etc (would be rad to see the artist name with the album and the artist name and album name with the track). PR has been updated, so fetch it and run it to see the changes. 

If all looks great merge away! I will see you guys after lunch.
- Carter

**Comment by Jessicashinjo** [comment]
I fetched it down and everything looks great! Thanks for working on the navBar! 🍧

**Comment by keithbradley1** [comment]
awesomesauce

**Pull request merged**
